# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Example override file for Mixtral 8x7B finetuning
#
# This config is optimized for instruction finetuning with lower learning rates
# and fewer training iterations compared to pretraining.

model:
  seq_length: 4096
  # MoE-specific parallelism settings
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1
  expert_model_parallel_size: 4
  # Enable sequence parallelism when TP > 1 for MoE models
  sequence_parallel: true
  # Recompute settings for memory efficiency
  recompute_granularity: "selective"
  recompute_method: "uniform"
  recompute_num_layers: 1

train:
  # Finetuning typically requires fewer iterations
  train_iters: 1000
  global_batch_size: 8
  micro_batch_size: 1
  eval_iters: 10
  eval_interval: 100

optimizer:
  # Lower learning rate for finetuning to avoid catastrophic forgetting
  lr: 0.00001
  min_lr: 0.000001

scheduler:
  lr_warmup_iters: 50
  # Optional: decay learning rate over the course of finetuning
  # lr_decay_iters: 1000

checkpoint:
  # Directory to save finetuned checkpoints
  save: /path/to/finetuned_checkpoints
  # Load pretrained checkpoint before finetuning
  load: /path/to/pretrained_checkpoint
  save_interval: 200
  ckpt_format: "torch_dist"
  fully_parallel_save: true

logger:
  log_interval: 10

dataset:
  sequence_length: 4096
  # For instruction finetuning, you typically want to mask loss on prompts
  # This is handled by the dataset implementation

rng:
  seed: 42

ddp:
  grad_reduce_in_fp32: true
  overlap_grad_reduce: true
  overlap_param_gather: true
  use_distributed_optimizer: true

# Optional: Enable LoRA for parameter-efficient finetuning
# NOTE: LoRA configuration would be added here when supported in the recipe
# lora:
#   lora_rank: 16
#   lora_alpha: 32
#   lora_target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
